# Generated by Django 5.2.4 on 2025-11-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='price',
            new_name='total_price',
        ),
    ]
